In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('df_06122022.csv')# voir parametres header=True

In [3]:
df.head()

,Unnamed: 0,self_employed,nb_employees,tech_company,role,healthcare_coverage,options_mental_health_care,mh_discuss,resources,anonymity_protected,...,interference_well_treated,interference_badly_treated,age,gender,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,work_position,remote_work
0,0,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,39,MALE,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,1,0,6-25,1.0,NaN,No,Yes,Yes,Yes,Yes,...,Rarely,Sometimes,29,MALE,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,2,0,6-25,1.0,NaN,No,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,38,MALE,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,MALE,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,4,0,6-25,0.0,1.0,Yes,Yes,No,No,No,...,Sometimes,Sometimes,43,FEMALE,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [4]:
df.isna().sum()

Unnamed: 0                                       0
self_employed                                    0
nb_employees                                   287
tech_company                                   287
role                                          1170
                                              ...
What US state or territory do you live in?     593
What country do you work in?                     0
What US state or territory do you work in?     582
work_position                                    0
remote_work                                      0
Length: 64, dtype: int64

In [84]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
df.shape

(1433, 64)

In [6]:
df['nb_employees'] = df['nb_employees'].fillna(df['nb_employees'].mode()[0])
df['tech_company'] = df['tech_company'].fillna(0)
df['role'] = df['role'].fillna(0)
df['healthcare_coverage'] = df['healthcare_coverage'].fillna("I don't know")
df['options_mental_health_care'] = df['options_mental_health_care'].fillna("I am not sure")
df['mh_discuss'] = df['mh_discuss'].fillna("I don't know")
df['resources']=df['resources'].fillna("I don't know")
df['anonymity_protected']=df['anonymity_protected'].fillna("I don't know")
df['asking_leave']=df['asking_leave'].fillna("I don't know")
df['discuss_mental']=df['discuss_mental'].fillna("Maybe")
df['discuss_physical']=df['discuss_physical'].fillna("Maybe")
df['discuss_coworkers']=df['discuss_coworkers'].fillna("Maybe")
df['discuss_supervisor']=df['discuss_supervisor'].fillna("Maybe")
df['mental_vs_physical']=df['mental_vs_physical'].fillna("I don't know")
df['negative_csqs_for_others']=df['negative_csqs_for_others'].fillna("No")
df['resources_for_help']=df['resources_for_help'].fillna("I know some")

df['if_yes_reveal_clients']=df['if_yes_reveal_clients'].fillna("Not applicable to me")
df['if_revealed_negative_impact_client']=df['if_revealed_negative_impact_client'].fillna("I'm not sure")
df['if_yes_reveal_coworkers']=df['if_yes_reveal_coworkers'].fillna("Not applicable to me")
df['if_revealed_coworkers_negative_impact']=df['if_revealed_coworkers_negative_impact'].fillna("I'm not sure")
df['productivity']=df['productivity'].fillna("Unsure")
df['percentage_of_work_time_affected']=df['percentage_of_work_time_affected'].fillna("1-25%")
df['previous employers']=df['previous employers'].fillna(1)
df['mental_health_benefits_prev']=df['mental_health_benefits_prev'].fillna("I don't know")
df['mh_discuss_prev']=df['mh_discuss_prev'].fillna("I don't know")
df['respurces_for_help_prev']=df['respurces_for_help_prev'].fillna("None did")
df['anonymity_protected_prev']=df['anonymity_protected_prev'].fillna("I don't know")
df['discuss_mental_prev']=df['discuss_mental_prev'].fillna("I don't know")
df['discuss_physical_prev']=df['discuss_physical_prev'].fillna("Some of them")
df['discuss_coworkers_prev']=df['discuss_coworkers_prev'].fillna("Some of my previous employers")
df['discuss_supervisor_prev']=df['discuss_supervisor_prev'].fillna("I don't know")
df['mental_vs_physical_prev']=df['mental_vs_physical_prev'].fillna("I don't know")
df['negative_csqs_for_others_prev']=df['negative_csqs_for_others_prev'].fillna("None of them")
df['physical_potential_employer']=df['physical_potential_employer'].fillna("Maybe")
df['mental_potential_employer']=df['mental_potential_employer'].fillna("Maybe")
df['identification']=df['identification'].fillna("Maybe")
df['share_with_coworkers']=df['share_with_coworkers'].fillna("Maybe")
df['share_with_family_friends']=df['share_with_family_friends'].fillna("Neutral")
df['bad_response']=df['bad_response'].fillna("Maybe/Not sure")
df['fear_through_bad_response']=df['fear_through_bad_response'].fillna("Maybe")
df['family_history']=df['family_history'].fillna("I don't know")
df['past_mental_disorder']=df['past_mental_disorder'].fillna("Maybe")
df['current_mental_disorder']=df['current_mental_disorder'].fillna("Maybe")
df['treatment']=df['treatment'].fillna(0)
df['interference_well_treated']=df['interference_well_treated'].fillna("Not applicable to me")
df['interference_badly_treated']=df['interference_badly_treated'].fillna("Not applicable to me")
df['work_position']=df['work_position'].fillna("Other")
df['remote_work']=df['remote_work'].fillna("Sometimes")

In [85]:
df.columns

Index(['self_employed', 'nb_employees', 'tech_company', 'role',
       'healthcare_coverage', 'options_mental_health_care', 'mh_discuss',
       'resources', 'anonymity_protected', 'asking_leave', 'discuss_mental',
       'discuss_physical', 'discuss_coworkers', 'discuss_supervisor',
       'mental_vs_physical', 'negative_csqs_for_others',
       'Do you have medical coverage (private insurance or state-provided) which includes treatment of Â mental health issues?',
       'resources_for_help', 'if_yes_reveal_clients',
       'if_revealed_negative_impact_client', 'if_yes_reveal_coworkers',
       'if_revealed_coworkers_negative_impact', 'productivity',
       'percentage_of_work_time_affected', 'previous employers',
       'mental_health_benefits_prev', 'options_prev', 'mh_discuss_prev',
       'respurces_for_help_prev', 'anonymity_protected_prev',
       'discuss_mental_prev', 'discuss_physical_prev',
       'discuss_coworkers_prev', 'discuss_supervisor_prev',
       'mental_vs_physical_prev', 'negative_csqs_for_others_prev',
       'physical_potential_employer', 'Why or why not?',
       'mental_potential_employer', 'Why or why not?.1', 'identification',
       'share_with_coworkers', 'share_with_family_friends', 'bad_response',
       'fear_through_bad_response', 'family_history', 'past_mental_disorder',
       'current_mental_disorder',
       'If yes, what condition(s) have you been diagnosed with?',
       'If maybe, what condition(s) do you believe you have?', 'diagnosis',
       'If so, what condition(s) were you diagnosed with?', 'treatment',
       'interference_well_treated', 'interference_badly_treated', 'age',
       'gender', 'What country do you live in?',
       'What US state or territory do you live in?',
       'What country do you work in?',
       'What US state or territory do you work in?', 'work_position',
       'remote_work', 'ishare_with_coworkers'],
      dtype='object')

In [86]:
df1=df.iloc[:, 0:16]

In [114]:
df1.head()

,self_employed,nb_employees,tech_company,role,healthcare_coverage,options_mental_health_care,mh_discuss,resources,anonymity_protected,asking_leave,discuss_mental,discuss_physical,discuss_coworkers,discuss_supervisor,mental_vs_physical,negative_csqs_for_others
0,0,26-100,1.0,0.0,Not eligible for coverage / N/A,I am not sure,No,No,I don't know,Very easy,No,No,Maybe,Yes,I don't know,No
1,0,6-25,1.0,0.0,No,Yes,Yes,Yes,Yes,Somewhat easy,No,No,Maybe,Yes,Yes,No
2,0,6-25,1.0,0.0,No,I am not sure,No,No,I don't know,Neither easy nor difficult,Maybe,No,Maybe,Maybe,I don't know,No
3,1,26-100,0.0,0.0,I don't know,I am not sure,I don't know,NaN,NaN,I don't know,Maybe,Maybe,Maybe,Maybe,I don't know,No
4,0,6-25,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,Yes,Maybe,Maybe,No,No,No

In [91]:
df2=df.iloc[:,17:63]

In [92]:
df2.head()

,resources_for_help,if_yes_reveal_clients,if_revealed_negative_impact_client,if_yes_reveal_coworkers,if_revealed_coworkers_negative_impact,productivity,percentage_of_work_time_affected,previous employers,mental_health_benefits_prev,options_prev,...,interference_well_treated,interference_badly_treated,age,gender,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,work_position,remote_work
0,I know some,NaN,I'm not sure,Not applicable to me,I'm not sure,Unsure,1-25%,1,"No, none did",N/A (not currently aware),...,Not applicable to me,Not applicable to me,39,MALE,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,I know some,NaN,I'm not sure,Not applicable to me,I'm not sure,Unsure,1-25%,1,"Yes, they all did",I was aware of some,...,Rarely,Sometimes,29,MALE,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,I know some,NaN,I'm not sure,Not applicable to me,I'm not sure,Unsure,1-25%,1,"No, none did",N/A (not currently aware),...,Not applicable to me,Not applicable to me,38,MALE,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,"Yes, I know several","Sometimes, if it comes up",I'm not sure,"Sometimes, if it comes up",I'm not sure,Yes,1-25%,1,Some did,N/A (not currently aware),...,Sometimes,Sometimes,43,MALE,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,I know some,NaN,I'm not sure,Not applicable to me,I'm not sure,Unsure,1-25%,1,I don't know,N/A (not currently aware),...,Sometimes,Sometimes,43,FEMALE,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [96]:
df=pd.concat([df1, df2])

In [98]:
df.head()

,self_employed,nb_employees,tech_company,role,healthcare_coverage,options_mental_health_care,mh_discuss,resources,anonymity_protected,asking_leave,...,interference_well_treated,interference_badly_treated,age,gender,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,work_position,remote_work
0,0.0,26-100,1.0,0.0,Not eligible for coverage / N/A,I am not sure,No,No,I don't know,Very easy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,6-25,1.0,0.0,No,Yes,Yes,Yes,Yes,Somewhat easy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,6-25,1.0,0.0,No,I am not sure,No,No,I don't know,Neither easy nor difficult,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,26-100,0.0,0.0,I don't know,I am not sure,I don't know,NaN,NaN,I don't know,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,6-25,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
data=pd.concat([df1, df2],axis=1)

In [100]:
data.shape

(1433, 62)

In [102]:
data.columns

Index(['self_employed', 'nb_employees', 'tech_company', 'role',
       'healthcare_coverage', 'options_mental_health_care', 'mh_discuss',
       'resources', 'anonymity_protected', 'asking_leave', 'discuss_mental',
       'discuss_physical', 'discuss_coworkers', 'discuss_supervisor',
       'mental_vs_physical', 'negative_csqs_for_others', 'resources_for_help',
       'if_yes_reveal_clients', 'if_revealed_negative_impact_client',
       'if_yes_reveal_coworkers', 'if_revealed_coworkers_negative_impact',
       'productivity', 'percentage_of_work_time_affected',
       'previous employers', 'mental_health_benefits_prev', 'options_prev',
       'mh_discuss_prev', 'respurces_for_help_prev',
       'anonymity_protected_prev', 'discuss_mental_prev',
       'discuss_physical_prev', 'discuss_coworkers_prev',
       'discuss_supervisor_prev', 'mental_vs_physical_prev',
       'negative_csqs_for_others_prev', 'physical_potential_employer',
       'Why or why not?', 'mental_potential_employer', 'Why or why not?.1',
       'identification', 'share_with_coworkers', 'share_with_family_friends',
       'bad_response', 'fear_through_bad_response', 'family_history',
       'past_mental_disorder', 'current_mental_disorder',
       'If yes, what condition(s) have you been diagnosed with?',
       'If maybe, what condition(s) do you believe you have?', 'diagnosis',
       'If so, what condition(s) were you diagnosed with?', 'treatment',
       'interference_well_treated', 'interference_badly_treated', 'age',
       'gender', 'What country do you live in?',
       'What US state or territory do you live in?',
       'What country do you work in?',
       'What US state or territory do you work in?', 'work_position',
       'remote_work'],
      dtype='object')

In [113]:
data.to_csv("data_15122022.csv")

In [107]:
data.head()

,self_employed,nb_employees,tech_company,role,healthcare_coverage,options_mental_health_care,mh_discuss,resources,anonymity_protected,asking_leave,...,interference_well_treated,interference_badly_treated,age,gender,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,work_position,remote_work
0,0,26-100,1.0,0.0,Not eligible for coverage / N/A,I am not sure,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,MALE,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,0,6-25,1.0,0.0,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,MALE,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,0,6-25,1.0,0.0,No,I am not sure,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,MALE,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,1,26-100,0.0,0.0,I don't know,I am not sure,I don't know,NaN,NaN,I don't know,...,Sometimes,Sometimes,43,MALE,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,0,6-25,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,...,Sometimes,Sometimes,43,FEMALE,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [105]:
data.isna().sum()

self_employed                                   0
nb_employees                                    0
tech_company                                    0
role                                            0
healthcare_coverage                             0
                                             ...
What US state or territory do you live in?    593
What country do you work in?                    0
What US state or territory do you work in?    582
work_position                                   0
remote_work                                     0
Length: 62, dtype: int64

In [8]:
df['resources_for_help'].value_counts()

I know some             141
Yes, I know several      83
No, I don't know any     63
Name: resources_for_help, dtype: int64

In [5]:
df['diagnosis'].value_counts()

No     717
Yes    716
Name: diagnosis, dtype: int64

In [6]:
df['diagnosis']=df['diagnosis'].map({'No':0, 'Yes':1}).astype(float)

In [111]:
df['anonymity_protected']=df['anonymity_protected'].fillna("I don't know")

In [81]:
df['What country do you live in?'].isna().sum()

0

In [103]:
data['age'].isna().sum()

0

In [104]:
data['gender'].value_counts()

MALE       1064
FEMALE      345
UNKNOWN      24
Name: gender, dtype: int64