In [52]:
import pandas as pd
import numpy as np

In [91]:
data=pd.read_csv("data_15122022.csv")

In [54]:
data.shape

(1433, 63)

In [55]:
data.columns

Index(['Unnamed: 0', 'self_employed', 'nb_employees', 'tech_company', 'role',
       'healthcare_coverage', 'options_mental_health_care', 'mh_discuss',
       'resources', 'anonymity_protected', 'asking_leave', 'discuss_mental',
       'discuss_physical', 'discuss_coworkers', 'discuss_supervisor',
       'mental_vs_physical', 'negative_csqs_for_others', 'resources_for_help',
       'if_yes_reveal_clients', 'if_revealed_negative_impact_client',
       'if_yes_reveal_coworkers', 'if_revealed_coworkers_negative_impact',
       'productivity', 'percentage_of_work_time_affected',
       'previous employers', 'mental_health_benefits_prev', 'options_prev',
       'mh_discuss_prev', 'respurces_for_help_prev',
       'anonymity_protected_prev', 'discuss_mental_prev',
       'discuss_physical_prev', 'discuss_coworkers_prev',
       'discuss_supervisor_prev', 'mental_vs_physical_prev',
       'negative_csqs_for_others_prev', 'physical_potential_employer',
       'Why or why not?', 'mental_potential_employer', 'Why or why not?.1',
       'identification', 'share_with_coworkers', 'share_with_family_friends',
       'bad_response', 'fear_through_bad_response', 'family_history',
       'past_mental_disorder', 'current_mental_disorder',
       'If yes, what condition(s) have you been diagnosed with?',
       'If maybe, what condition(s) do you believe you have?', 'diagnosis',
       'If so, what condition(s) were you diagnosed with?', 'treatment',
       'interference_well_treated', 'interference_badly_treated', 'age',
       'gender', 'What country do you live in?',
       'What US state or territory do you live in?',
       'What country do you work in?',
       'What US state or territory do you work in?', 'work_position',
       'remote_work'],
      dtype='object')

In [92]:
data.drop('Unnamed: 0', axis=1, inplace=True)

In [156]:
#data=data.join(pd.get_dummies(data['healthcare_coverage'],prefix='healthcare'))

In [93]:
data.columns

Index(['self_employed', 'nb_employees', 'tech_company', 'role',
       'healthcare_coverage', 'options_mental_health_care', 'mh_discuss',
       'resources', 'anonymity_protected', 'asking_leave', 'discuss_mental',
       'discuss_physical', 'discuss_coworkers', 'discuss_supervisor',
       'mental_vs_physical', 'negative_csqs_for_others', 'resources_for_help',
       'if_yes_reveal_clients', 'if_revealed_negative_impact_client',
       'if_yes_reveal_coworkers', 'if_revealed_coworkers_negative_impact',
       'productivity', 'percentage_of_work_time_affected',
       'previous employers', 'mental_health_benefits_prev', 'options_prev',
       'mh_discuss_prev', 'respurces_for_help_prev',
       'anonymity_protected_prev', 'discuss_mental_prev',
       'discuss_physical_prev', 'discuss_coworkers_prev',
       'discuss_supervisor_prev', 'mental_vs_physical_prev',
       'negative_csqs_for_others_prev', 'physical_potential_employer',
       'Why or why not?', 'mental_potential_employer', 'Why or why not?.1',
       'identification', 'share_with_coworkers', 'share_with_family_friends',
       'bad_response', 'fear_through_bad_response', 'family_history',
       'past_mental_disorder', 'current_mental_disorder',
       'If yes, what condition(s) have you been diagnosed with?',
       'If maybe, what condition(s) do you believe you have?', 'diagnosis',
       'If so, what condition(s) were you diagnosed with?', 'treatment',
       'interference_well_treated', 'interference_badly_treated', 'age',
       'gender', 'What country do you live in?',
       'What US state or territory do you live in?',
       'What country do you work in?',
       'What US state or territory do you work in?', 'work_position',
       'remote_work'],
      dtype='object')

In [56]:
data.shape

(1433, 63)

In [94]:
#Suppression des valeurs en free text
data.drop('Why or why not?', axis=1, inplace=True)
data.drop('Why or why not?.1', axis=1, inplace=True)
data.drop('If yes, what condition(s) have you been diagnosed with?', axis=1, inplace=True)
data.drop('If maybe, what condition(s) do you believe you have?', axis=1, inplace=True)
data.drop('If so, what condition(s) were you diagnosed with?', axis=1, inplace=True)

In [58]:
data.shape

(1433, 58)

In [ ]:
# Ordinal encoding parce qu'il y a un ordre: colonnes 'nb_employees' et 'percentage_of_work_time_affected'

In [12]:
data['nb_employees'].value_counts()

26-100            579
More than 1000    256
100-500           248
6-25              210
500-1000           80
1-5                60
Name: nb_employees, dtype: int64

In [95]:
data['nb_employees'] = data['nb_employees'].map({'1-5':0,
                             '6-25':1,
                             '26-100':2, 
                             '100-500':3,
                             '500-1000':4,
                             'More than 1000':5})

In [14]:
data['percentage_of_work_time_affected'].value_counts()

1-25%      1321
26-50%       72
51-75%       26
76-100%      14
Name: percentage_of_work_time_affected, dtype: int64

In [96]:
data['percentage_of_work_time_affected']=data['percentage_of_work_time_affected'].map({'1-25%':0,
                             '26-50%':1,
                             '51-75%':2, 
                             '76-100%':3})

In [ ]:
# Valeurs qui n'ont pas besoin d'être changées car ce sont déjà des valeurs 0/1

In [98]:
data['self_employed'].value_counts()

0    1146
1     287
Name: self_employed, dtype: int64

In [99]:
data['treatment'].value_counts()

1    839
0    594
Name: treatment, dtype: int64

In [100]:
data['tech_company'].value_counts()

1.0    883
0.0    550
Name: tech_company, dtype: int64

In [101]:
data['role'].value_counts()

0.0    1185
1.0     248
Name: role, dtype: int64

In [102]:
data.shape

(1433, 57)

In [ ]:
#Séparation de la cible et du reste

In [112]:
data['diagnosis'].dtype

dtype('O')

In [308]:
#data.drop('diagnosis', axis=1, inplace=True)

In [290]:
#target.dtype

dtype('O')

In [103]:
var_cat=data.select_dtypes(include=['O'])

In [111]:
data['diagnosis']=data['diagnosis'].map({'No':0, 'Yes':1}).astype(float)

KeyError: 'diagnosis'

In [105]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder( drop="first", sparse=False,max_categories=20)
var_cat_o = ohe.fit_transform(var_cat)

In [106]:
var_cat = pd.DataFrame(var_cat_o,columns=ohe.get_feature_names_out(var_cat.columns))

In [107]:
var_cat.columns.to_list()

['healthcare_coverage_No',
 'healthcare_coverage_Not eligible for coverage / N/A',
 'healthcare_coverage_Yes',
 'options_mental_health_care_No',
 'options_mental_health_care_Yes',
 'mh_discuss_No',
 'mh_discuss_Yes',
 'resources_No',
 'resources_Yes',
 'resources_nan',
 'anonymity_protected_No',
 'anonymity_protected_Yes',
 'anonymity_protected_nan',
 'asking_leave_Neither easy nor difficult',
 'asking_leave_Somewhat difficult',
 'asking_leave_Somewhat easy',
 'asking_leave_Very difficult',
 'asking_leave_Very easy',
 'discuss_mental_No',
 'discuss_mental_Yes',
 'discuss_physical_No',
 'discuss_physical_Yes',
 'discuss_coworkers_No',
 'discuss_coworkers_Yes',
 'discuss_supervisor_No',
 'discuss_supervisor_Yes',
 'mental_vs_physical_No',
 'mental_vs_physical_Yes',
 'negative_csqs_for_others_Yes',
 "resources_for_help_No, I don't know any",
 'resources_for_help_Yes, I know several',
 'if_yes_reveal_clients_No, because it would impact me negatively',
 'if_yes_reveal_clients_Not applicable to me',
 'if_yes_reveal_clients_Sometimes, if it comes up',
 'if_yes_reveal_clients_Yes, always',
 'if_yes_reveal_clients_nan',
 'if_revealed_negative_impact_client_No',
 'if_revealed_negative_impact_client_Yes',
 'if_yes_reveal_coworkers_No, because it would impact me negatively',
 'if_yes_reveal_coworkers_Not applicable to me',
 'if_yes_reveal_coworkers_Sometimes, if it comes up',
 'if_yes_reveal_coworkers_Yes, always',
 'if_revealed_coworkers_negative_impact_No',
 'if_revealed_coworkers_negative_impact_Not applicable to me',
 'if_revealed_coworkers_negative_impact_Yes',
 'productivity_Not applicable to me',
 'productivity_Unsure',
 'productivity_Yes',
 'mental_health_benefits_prev_No, none did',
 'mental_health_benefits_prev_Some did',
 'mental_health_benefits_prev_Yes, they all did',
 'options_prev_N/A (not currently aware)',
 'options_prev_No, I only became aware later',
 'options_prev_Yes, I was aware of all of them',
 'mh_discuss_prev_None did',
 'mh_discuss_prev_Some did',
 'mh_discuss_prev_Yes, they all did',
 'respurces_for_help_prev_Some did',
 'respurces_for_help_prev_Yes, they all did',
 'anonymity_protected_prev_No',
 'anonymity_protected_prev_Sometimes',
 'anonymity_protected_prev_Yes, always',
 'discuss_mental_prev_None of them',
 'discuss_mental_prev_Some of them',
 'discuss_mental_prev_Yes, all of them',
 'discuss_physical_prev_Some of them',
 'discuss_physical_prev_Yes, all of them',
 'discuss_coworkers_prev_Some of my previous employers',
 'discuss_coworkers_prev_Yes, at all of my previous employers',
 'discuss_supervisor_prev_No, at none of my previous employers',
 'discuss_supervisor_prev_Some of my previous employers',
 'discuss_supervisor_prev_Yes, at all of my previous employers',
 'mental_vs_physical_prev_None did',
 'mental_vs_physical_prev_Some did',
 'mental_vs_physical_prev_Yes, they all did',
 'negative_csqs_for_others_prev_Some of them',
 'negative_csqs_for_others_prev_Yes, all of them',
 'physical_potential_employer_No',
 'physical_potential_employer_Yes',
 'mental_potential_employer_No',
 'mental_potential_employer_Yes',
 "identification_No, I don't think it would",
 'identification_No, it has not',
 'identification_Yes, I think it would',
 'identification_Yes, it has',
 "share_with_coworkers_No, I don't think they would",
 'share_with_coworkers_No, they do not',
 'share_with_coworkers_Yes, I think they would',
 'share_with_coworkers_Yes, they do',
 'share_with_family_friends_Not applicable to me (I do not have a mental illness)',
 'share_with_family_friends_Not open at all',
 'share_with_family_friends_Somewhat not open',
 'share_with_family_friends_Somewhat open',
 'share_with_family_friends_Very open',
 'bad_response_No',
 'bad_response_Yes, I experienced',
 'bad_response_Yes, I observed',
 'fear_through_bad_response_No',
 'fear_through_bad_response_Yes',
 'family_history_No',
 'family_history_Yes',
 'past_mental_disorder_No',
 'past_mental_disorder_Yes',
 'current_mental_disorder_No',
 'current_mental_disorder_Yes',
 'diagnosis_Yes',
 'interference_well_treated_Not applicable to me',
 'interference_well_treated_Often',
 'interference_well_treated_Rarely',
 'interference_well_treated_Sometimes',
 'interference_badly_treated_Not applicable to me',
 'interference_badly_treated_Often',
 'interference_badly_treated_Rarely',
 'interference_badly_treated_Sometimes',
 'gender_MALE',
 'gender_UNKNOWN',
 'What country do you live in?_Belgium',
 'What country do you live in?_Brazil',
 'What country do you live in?_Bulgaria',
 'What country do you live in?_Canada',
 'What country do you live in?_Denmark',
 'What country do you live in?_Finland',
 'What country do you live in?_France',
 'What country do you live in?_Germany',
 'What country do you live in?_India',
 'What country do you live in?_Ireland',
 'What country do you live in?_Italy',
 'What country do you live in?_Netherlands',
 'What country do you live in?_New Zealand',
 'What country do you live in?_Russia',
 'What country do you live in?_Sweden',
 'What country do you live in?_Switzerland',
 'What country do you live in?_United Kingdom',
 'What country do you live in?_United States of America',
 'What country do you live in?_infrequent_sklearn',
 'What US state or territory do you live in?_Colorado',
 'What US state or territory do you live in?_Florida',
 'What US state or territory do you live in?_Illinois',
 'What US state or territory do you live in?_Indiana',
 'What US state or territory do you live in?_Maryland',
 'What US state or territory do you live in?_Massachusetts',
 'What US state or territory do you live in?_Michigan',
 'What US state or territory do you live in?_Minnesota',
 'What US state or territory do you live in?_New York',
 'What US state or territory do you live in?_North Carolina',
 'What US state or territory do you live in?_Ohio',
 'What US state or territory do you live in?_Oregon',
 'What US state or territory do you live in?_Pennsylvania',
 'What US state or territory do you live in?_Tennessee',
 'What US state or territory do you live in?_Texas',
 'What US state or territory do you live in?_Virginia',
 'What US state or territory do you live in?_Washington',
 'What US state or territory do you live in?_nan',
 'What US state or territory do you live in?_infrequent_sklearn',
 'What country do you work in?_Belgium',
 'What country do you work in?_Brazil',
 'What country do you work in?_Bulgaria',
 'What country do you work in?_Canada',
 'What country do you work in?_Denmark',
 'What country do you work in?_Finland',
 'What country do you work in?_France',
 'What country do you work in?_Germany',
 'What country do you work in?_India',
 'What country do you work in?_Ireland',
 'What country do you work in?_Netherlands',
 'What country do you work in?_New Zealand',
 'What country do you work in?_Russia',
 'What country do you work in?_South Africa',
 'What country do you work in?_Sweden',
 'What country do you work in?_Switzerland',
 'What country do you work in?_United Kingdom',
 'What country do you work in?_United States of America',
 'What country do you work in?_infrequent_sklearn',
 'What US state or territory do you work in?_Colorado',
 'What US state or territory do you work in?_Florida',
 'What US state or territory do you work in?_Illinois',
 'What US state or territory do you work in?_Indiana',
 'What US state or territory do you work in?_Massachusetts',
 'What US state or territory do you work in?_Michigan',
 'What US state or territory do you work in?_Minnesota',
 'What US state or territory do you work in?_New York',
 'What US state or territory do you work in?_North Carolina',
 'What US state or territory do you work in?_Ohio',
 'What US state or territory do you work in?_Oklahoma',
 'What US state or territory do you work in?_Oregon',
 'What US state or territory do you work in?_Pennsylvania',
 'What US state or territory do you work in?_Tennessee',
 'What US state or territory do you work in?_Texas',
 'What US state or territory do you work in?_Washington',
 'What US state or territory do you work in?_Wisconsin',
 'What US state or territory do you work in?_nan',
 'What US state or territory do you work in?_infrequent_sklearn',
 'work_position_Back-end Developer|DevOps/SysAdmin',
 'work_position_Back-end Developer|Front-end Developer',
 'work_position_Designer',
 'work_position_Dev Evangelist/Advocate',
 'work_position_DevOps/SysAdmin',
 'work_position_DevOps/SysAdmin|Back-end Developer',
 'work_position_DevOps/SysAdmin|Back-end Developer|Front-end Developer',
 'work_position_Executive Leadership',
 'work_position_Front-end Developer',
 'work_position_Front-end Developer|Back-end Developer',
 'work_position_Front-end Developer|Back-end Developer|DevOps/SysAdmin',
 'work_position_Front-end Developer|Designer',
 'work_position_One-person shop',
 'work_position_Other',
 'work_position_Supervisor/Team Lead',
 'work_position_Supervisor/Team Lead|Back-end Developer',
 'work_position_Supervisor/Team Lead|Back-end Developer|Front-end Developer',
 'work_position_Support',
 'work_position_infrequent_sklearn',
 'remote_work_Never',
 'remote_work_Sometimes']

In [115]:
var_num=data.select_dtypes(include=['int', 'float'])

In [116]:
var_num

,self_employed,nb_employees,tech_company,role,percentage_of_work_time_affected,previous employers,diagnosis,treatment,age
0,0,2,1.0,0.0,0,1,1.0,0,39
1,0,1,1.0,0.0,0,1,1.0,1,29
2,0,1,1.0,0.0,0,1,0.0,1,38
3,1,2,0.0,0.0,0,1,1.0,1,43
4,0,1,0.0,1.0,0,1,1.0,1,43
...,...,...,...,...,...,...,...,...,...
1428,1,2,0.0,0.0,0,1,0.0,1,34
1429,1,2,0.0,0.0,0,0,1.0,0,56
1430,0,3,1.0,0.0,0,1,1.0,1,52
1431,0,3,0.0,1.0,0,1,1.0,0,30
1432,0,3,1.0,0.0,0,0,0.0,0,25

In [81]:
var_num.isna().sum().sum()

0

In [309]:
#data.head()

,self_employed,nb_employees,tech_company,role,healthcare_coverage,options_mental_health_care,mh_discuss,resources,anonymity_protected,asking_leave,...,fear_through_bad_response,family_history,past_mental_disorder,current_mental_disorder,treatment,interference_well_treated,interference_badly_treated,age,gender,remote_work
0,0,2,1.0,0.0,Not eligible for coverage / N/A,I am not sure,No,No,I don't know,Very easy,...,Maybe,No,Yes,No,0,Not applicable to me,Not applicable to me,39,MALE,Sometimes
1,0,1,1.0,0.0,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Maybe,Yes,Yes,Yes,1,Rarely,Sometimes,29,MALE,Never
2,0,1,1.0,0.0,No,I am not sure,No,No,I don't know,Neither easy nor difficult,...,Yes,No,Maybe,No,1,Not applicable to me,Not applicable to me,38,MALE,Always
3,1,2,0.0,0.0,I don't know,I am not sure,I don't know,NaN,NaN,I don't know,...,Maybe,No,Yes,Yes,1,Sometimes,Sometimes,43,MALE,Sometimes
4,0,1,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,...,Yes,Yes,Yes,Yes,1,Sometimes,Sometimes,43,FEMALE,Sometimes

In [ ]:
# One Hot Encoding

In [88]:
#def ohe(arg):
#    data.join(pd.get_dummies(arg,prefix=arg))
#   data.drop(arg, axis=1, inplace=True)
#   return ('Done')

In [89]:
#ohe('previous employers')

'Done'

In [332]:
#final=pd.get_dummies(data, columns=cols)

In [117]:
final= pd.concat([var_num,var_cat], axis = 1)

In [335]:
#final.to_csv('final_19122022.csv')

In [119]:
final['treatment']

0       0
1       1
2       1
3       1
4       1
       ..
1428    1
1429    0
1430    1
1431    0
1432    0
Name: treatment, Length: 1433, dtype: int64

In [114]:
data['diagnosis']=data['diagnosis'].map({'No':0, 'Yes':1}).astype(float)

In [124]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1433 entries, 0 to 1432
Columns: 222 entries, self_employed to remote_work_Sometimes
dtypes: float64(216), int64(6)
memory usage: 2.4 MB

In [125]:
final.to_csv('final_211222.csv')

In [120]:
target = final['diagnosis']
feats=final.drop('diagnosis', axis=1)

In [121]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feats, target, test_size=0.2)

In [123]:
display(X_test)

,self_employed,nb_employees,tech_company,role,percentage_of_work_time_affected,previous employers,treatment,age,healthcare_coverage_No,healthcare_coverage_Not eligible for coverage / N/A,...,work_position_Front-end Developer|Designer,work_position_One-person shop,work_position_Other,work_position_Supervisor/Team Lead,work_position_Supervisor/Team Lead|Back-end Developer,work_position_Supervisor/Team Lead|Back-end Developer|Front-end Developer,work_position_Support,work_position_infrequent_sklearn,remote_work_Never,remote_work_Sometimes
527,0,1,0.0,1.0,0,1,1,38,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
458,0,1,1.0,0.0,0,1,0,29,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
253,0,2,1.0,0.0,0,1,1,30,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
159,0,4,1.0,0.0,0,1,0,25,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
208,0,1,1.0,0.0,0,1,1,44,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,0,2,1.0,0.0,0,1,0,27,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
388,0,5,1.0,0.0,0,1,1,24,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
145,1,2,0.0,0.0,0,1,0,40,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
202,0,4,1.0,0.0,0,1,0,24,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1239,1,2,0.0,0.0,0,1,1,39,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [71]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(sparse=False, max_categories=20)

OHE.fit_transform(X_train,y_train)



#OHE.transform(X_test,y_test)

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [72]:
OHE.transform(X_test,y_test)

TypeError: transform() takes 2 positional arguments but 3 were given

In [50]:
#Notes

,self_employed,nb_employees,tech_company,role,healthcare_coverage,options_mental_health_care,mh_discuss,resources,anonymity_protected,asking_leave,...,interference_well_treated,interference_badly_treated,age,gender,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,work_position,remote_work
991,False,5,True,False,Yes,I am not sure,Yes,Yes,I don't know,Somewhat difficult,...,Not applicable to me,Not applicable to me,32,MALE,United States of America,Washington,United States of America,Washington,Front-end Developer,Sometimes
16,False,2,True,False,Not eligible for coverage / N/A,No,No,No,I don't know,Very difficult,...,Sometimes,Often,32,FEMALE,Canada,NaN,Canada,NaN,Front-end Developer,Always
240,False,3,True,False,Not eligible for coverage / N/A,I am not sure,Yes,No,I don't know,Neither easy nor difficult,...,Rarely,Often,34,MALE,Germany,NaN,Germany,NaN,Front-end Developer,Never
750,False,5,False,True,No,I am not sure,No,No,I don't know,Very difficult,...,Often,Often,28,UNKNOWN,United Kingdom,NaN,United Kingdom,NaN,Support,Never
829,False,1,True,False,I don't know,I am not sure,No,No,I don't know,I don't know,...,Not applicable to me,Not applicable to me,37,MALE,United States of America,Minnesota,United States of America,Minnesota,Executive Leadership|Supervisor/Team Lead|Back...,Sometimes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,False,3,False,True,No,I am not sure,No,No,I don't know,I don't know,...,Never,Sometimes,33,MALE,Brazil,NaN,Brazil,NaN,Other,Never
353,True,2,False,False,I don't know,I am not sure,I don't know,NaN,NaN,I don't know,...,Not applicable to me,Rarely,39,MALE,Denmark,NaN,Denmark,NaN,Front-end Developer|Back-end Developer|DevOps/...,Sometimes
359,False,3,True,False,Yes,I am not sure,No,No,I don't know,I don't know,...,Sometimes,Often,29,MALE,United States of America,Michigan,United States of America,California,Back-end Developer,Always
1062,False,3,True,False,Not eligible for coverage / N/A,I am not sure,Yes,No,I don't know,Somewhat difficult,...,Rarely,Often,31,UNKNOWN,Switzerland,NaN,Switzerland,NaN,Back-end Developer,Never
969,False,2,True,False,No,I am not sure,No,No,I don't know,Very easy,...,Rarely,Often,30,MALE,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes

In [1]:
import sklearn
sklearn.__version__

'1.1.3'